export const EMOTIONS = [
  {
    id: 21,
    name: 'Joy',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 22,
    name: 'Love',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 23,
    name: 'Excitement',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 24,
    name: 'Amusement',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 25,
    name: 'Awe',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 26,
    name: 'Euphoria',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 27,
    name: 'Wonder',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 28,
    name: 'Admiration',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 29,
    name: 'Reverence',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 210,
    name: 'Optimism',
    type: 'Joy',
    category: 'EMOTION',
  },
  {
    id: 211,
    name: 'Sadness',
    type: 'Grief',
    category: 'EMOTION',
  },
  {
    id: 212,
    name: 'Despair',
    type: 'Grief',
    category: 'EMOTION',
  },
  {
    id: 213,
    name: 'Nostalgia',
    type: 'Grief',
    category: 'EMOTION',
  },
  {
    id: 214,
    name: 'Anger',
    type: 'Frustration',
    category: 'EMOTION',
  },
  {
    id: 215,
    name: 'Frustration',
    type: 'Frustration',
    category: 'EMOTION',
  },
  {
    id: 216,
    name: 'Indignation',
    type: 'Frustration',
    category: 'EMOTION',
  },
  {
    id: 217,
    name: 'Resentment',
    type: 'Frustration',
    category: 'EMOTION',
  },
  {
    id: 217,
    name: 'Surprise',
    type: 'Surprise',
    category: 'EMOTION',
  },
  {
    id: 218,
    name: 'Wonder',
    type: 'Surprise',
    category: 'EMOTION',
  },
  {
    id: 219,
    name: 'Awe',
    type: 'Surprise',
    category: 'EMOTION',
  },
  {
    id: 220,
    name: 'Disgust',
    type: 'Contempt',
    category: 'EMOTION',
  },
  {
    id: 221,
    name: 'Contempt',
    type: 'Contempt',
    category: 'EMOTION',
  },
  {
    id: 222,
    name: 'Anticipation',
    type: 'Anticipation',
    category: 'EMOTION',
  },
  {
    id: 223,
    name: 'Hope',
    type: 'Anticipation',
    category: 'EMOTION',
  },
  {
    id: 224,
    name: 'Satisfaction',
    type: 'Anticipation',
    category: 'EMOTION',
  },
  {
    id: 225,
    name: 'Relief',
    type: 'Anticipation',
    category: 'EMOTION',
  },
  {
    id: 226,
    name: 'Envy',
    type: 'Jealousy',
    category: 'EMOTION',
  },
  {
    id: 227,
    name: 'Jealousy',
    type: 'Jealousy',
    category: 'EMOTION',
  },
  {
    id: 228,
    name: 'Greed',
    type: 'Jealousy',
    category: 'EMOTION',
  },
  {
    id: 229,
    name: 'Empathy',
    type: 'Empathy',
    category: 'EMOTION',
  },
  {
    id: 230,
    name: 'Sympathy',
    type: 'Empathy',
    category: 'EMOTION',
  },
  {
    id: 231,
    name: 'Confusion',
    type: 'Curiosity',
    category: 'EMOTION',
  },
  {
    id: 232,
    name: 'Curiosity',
    type: 'Curiosity',
    category: 'EMOTION',
  },
  {
    id: 233,
    name: 'Skepticism',
    type: 'Curiosity',
    category: 'EMOTION',
  },
];
