export const GENRES = [
  { id: 41, name: 'News', category: 'GENRE' },
  { id: 42, name: 'Opinion/Editorial', category: 'GENRE' },
  { id: 43, name: 'Lifestyle/Fashion', category: 'GENRE' },
  { id: 44, name: 'Health/Fitness', category: 'GENRE' },
  { id: 45, name: 'Entertainment/Celebrity gossip', category: 'GENRE' },
  { id: 46, name: 'Technology/Science', category: 'GENRE' },
  { id: 47, name: 'Sports', category: 'GENRE' },
  { id: 48, name: 'Travel', category: 'GENRE' },
  { id: 49, name: 'Food/Cooking', category: 'GENRE' },
  { id: 410, name: 'Business/Finance', category: 'GENRE' },
  { id: 411, name: 'Education', category: 'GENRE' },
  { id: 412, name: 'Politics/Government', category: 'GENRE' },
  { id: 413, name: 'Automotive', category: 'GENRE' },
  { id: 414, name: 'Home/Garden', category: 'GENRE' },
  { id: 415, name: 'Pets/Animals', category: 'GENRE' },
];
