export const PERSONAS = [
  { id: 1, name: 'Adventurous', type: 'Outgoing' },
  { id: 2, name: 'Enthusiastic', type: 'Outgoing' },
  { id: 3, name: 'Extroverted', type: 'Outgoing' },
  { id: 4, name: 'Outgoing', type: 'Outgoing' },
  { id: 5, name: 'Analytical', type: 'Analytical' },
  { id: 6, name: 'Introspective', type: 'Analytical' },
  { id: 7, name: 'Logical', type: 'Analytical' },
  { id: 8, name: 'Perfectionist', type: 'Analytical' },
  { id: 24, name: 'Organized', type: 'Analytical' },
  { id: 9, name: 'Artistic', type: 'Visionary' },
  { id: 10, name: 'Creative', type: 'Visionary' },
  { id: 11, name: 'Innovative', type: 'Visionary' },
  { id: 12, name: 'Visionary', type: 'Visionary' },
  { id: 13, name: 'Ambitious', type: 'Visionary' },
  { id: 14, name: 'Determined', type: 'Determined' },
  { id: 15, name: 'Competitive', type: 'Determined' },
  { id: 16, name: 'Confident', type: 'Determined' },
  { id: 17, name: 'Assertive', type: 'Determined' },
  { id: 18, name: 'Caring', type: 'Empathetic' },
  { id: 19, name: 'Curious', type: 'Empathetic' },
  { id: 20, name: 'Easygoing', type: 'Empathetic' },
  { id: 21, name: 'Empathetic', type: 'Empathetic' },
  { id: 22, name: 'Independent', type: 'Empathetic' },
  { id: 23, name: 'Optimistic', type: 'Empathetic' },
  { id: 25, name: 'Reserved', type: 'Empathetic' },
];
