export const PERSONAS = [
  { id: 31, name: 'Adventurous', type: 'Outgoing', category: 'PERSONA' },
  { id: 32, name: 'Enthusiastic', type: 'Outgoing', category: 'PERSONA' },
  { id: 33, name: 'Extroverted', type: 'Outgoing', category: 'PERSONA' },
  { id: 34, name: 'Outgoing', type: 'Outgoing', category: 'PERSONA' },
  { id: 35, name: 'Analytical', type: 'Analytical', category: 'PERSONA' },
  { id: 36, name: 'Introspective', type: 'Analytical', category: 'PERSONA' },
  { id: 37, name: 'Logical', type: 'Analytical', category: 'PERSONA' },
  { id: 38, name: 'Perfectionist', type: 'Analytical', category: 'PERSONA' },
  { id: 324, name: 'Organized', type: 'Analytical', category: 'PERSONA' },
  { id: 39, name: 'Artistic', type: 'Visionary', category: 'PERSONA' },
  { id: 310, name: 'Creative', type: 'Visionary', category: 'PERSONA' },
  { id: 311, name: 'Innovative', type: 'Visionary', category: 'PERSONA' },
  { id: 312, name: 'Visionary', type: 'Visionary', category: 'PERSONA' },
  { id: 313, name: 'Ambitious', type: 'Visionary', category: 'PERSONA' },
  { id: 314, name: 'Determined', type: 'Determined', category: 'PERSONA' },
  { id: 315, name: 'Competitive', type: 'Determined', category: 'PERSONA' },
  { id: 316, name: 'Confident', type: 'Determined', category: 'PERSONA' },
  { id: 317, name: 'Assertive', type: 'Determined', category: 'PERSONA' },
  { id: 318, name: 'Caring', type: 'Empathetic', category: 'PERSONA' },
  { id: 319, name: 'Curious', type: 'Empathetic', category: 'PERSONA' },
  { id: 320, name: 'Easygoing', type: 'Empathetic', category: 'PERSONA' },
  { id: 321, name: 'Empathetic', type: 'Empathetic', category: 'PERSONA' },
  { id: 322, name: 'Independent', type: 'Empathetic', category: 'PERSONA' },
  { id: 323, name: 'Optimistic', type: 'Empathetic', category: 'PERSONA' },
  { id: 325, name: 'Reserved', type: 'Empathetic', category: 'PERSONA' },
];
