export const TONES = [
  {
    id: 11,
    name: 'Formal',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 12,
    name: 'Professional',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 14,
    name: 'Authoritative',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 15,
    name: 'Commanding',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 16,
    name: 'Professional',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 17,
    name: 'Detached',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 18,
    name: 'Analytical',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 19,
    name: 'Logical',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 110,
    name: 'Diplomatic',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 111,
    name: 'Respectful',
    type: 'Professionalism',
    category: 'TONE',
  },
  {
    id: 112,
    name: 'Sincere',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 113,
    name: 'Empathetic',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 114,
    name: 'Compassionate',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 115,
    name: 'Patient',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 116,
    name: 'Understanding',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 117,
    name: 'Concerned',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 118,
    name: 'Worried',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 119,
    name: 'Encouraging',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 120,
    name: 'Supportive',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 121,
    name: 'Nurturing',
    type: 'Empathy',
    category: 'TONE',
  },
  {
    id: 122,
    name: 'Sarcastic',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 123,
    name: 'Witty',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 124,
    name: 'Humorous',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 125,
    name: 'Playful',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 126,
    name: 'Ironic',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 127,
    name: 'Breezy',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 128,
    name: 'Light-hearted',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 129,
    name: 'Sarcastic',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 130,
    name: 'Witty',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 131,
    name: 'Humorous',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 132,
    name: 'Playful',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 133,
    name: 'Ironic',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 134,
    name: 'Breezy',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 135,
    name: 'Light-hearted',
    type: 'Playfulness',
    category: 'TONE',
  },
  {
    id: 136,
    name: 'Reflective',
    type: 'Introspection',
    category: 'TONE',
  },
  {
    id: 137,
    name: 'Introspective',
    type: 'Introspection',
    category: 'TONE',
  },
  {
    id: 138,
    name: 'Wistful',
    type: 'Introspection',
    category: 'TONE',
  },
  {
    id: 139,
    name: 'Nostalgic',
    type: 'Introspection',
    category: 'TONE',
  },
  {
    id: 140,
    name: 'Soothing',
    type: 'Introspection',
    category: 'TONE',
  },
  {
    id: 141,
    name: 'Calming',
    type: 'Introspection',
    category: 'TONE',
  },
  {
    id: 142,
    name: 'Assertive',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 143,
    name: 'Determined',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 144,
    name: 'Confident',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 145,
    name: 'Defensive',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 146,
    name: 'Guarded',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 147,
    name: 'Arrogant',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 148,
    name: 'Egotistical',
    type: 'Confidence',
    category: 'TONE',
  },
  {
    id: 149,
    name: 'Inquisitive',
    type: 'Curiosity',
    category: 'TONE',
  },
  {
    id: 150,
    name: 'Curious',
    type: 'Curiosity',
    category: 'TONE',
  },
  {
    id: 151,
    name: 'Analytical',
    type: 'Curiosity',
    category: 'TONE',
  },
  {
    id: 152,
    name: 'Logical',
    type: 'Curiosity',
    category: 'TONE',
  },
  {
    id: 153,
    name: 'Friendly',
    type: 'Affection',
    category: 'TONE',
  },
  {
    id: 154,
    name: 'Welcoming',
    type: 'Affection',
    category: 'TONE',
  },
  {
    id: 155,
    name: 'Affectionate',
    type: 'Affection',
    category: 'TONE',
  },
  {
    id: 156,
    name: 'Loving',
    type: 'Affection',
    category: 'TONE',
  },
  {
    id: 157,
    name: 'Polite',
    type: 'Respect',
    category: 'TONE',
  },
  {
    id: 158,
    name: 'Courteous',
    type: 'Respect',
    category: 'TONE',
  },
  {
    id: 159,
    name: 'Diplomatic',
    type: 'Respect',
    category: 'TONE',
  },
  {
    id: 160,
    name: 'Tactful',
    type: 'Respect',
    category: 'TONE',
  },
  {
    id: 161,
    name: 'Respectful',
    type: 'Respect',
    category: 'TONE',
  },
  {
    id: 162,
    name: 'Casual',
    type: 'Casual',
    category: 'TONE',
  },
  {
    id: 163,
    name: 'Conversational',
    type: 'Casual',
    category: 'TONE',
  },
  {
    id: 164,
    name: 'Relaxed',
    type: 'Casual',
    category: 'TONE',
  },
  {
    id: 165,
    name: 'Breezy',
    type: 'Casual',
    category: 'TONE',
  },
  {
    id: 166,
    name: 'Light-hearted',
    type: 'Casual',
    category: 'TONE',
  },
  {
    id: 167,
    name: 'Calm',
    type: 'Casual',
    category: 'TONE',
  },
  {
    id: 167,
    name: 'Cynical',
    type: 'Negativity',
    category: 'TONE',
  },
  {
    id: 168,
    name: 'Pessimistic',
    type: 'Negativity',
    category: 'TONE',
  },
  {
    id: 169,
    name: 'Sarcastic',
    type: 'Negativity',
    category: 'TONE',
  },
  {
    id: 170,
    name: 'Critical',
    type: 'Negativity',
    category: 'TONE',
  },
  {
    id: 171,
    name: 'Judgmental',
    type: 'Negativity',
    category: 'TONE',
  },
  {
    id: 172,
    name: 'Stressed',
    type: 'Negativity',
    category: 'TONE',
  },
  {
    id: 173,
    name: 'Anxious',
    type: 'Negativity',
    category: 'TONE',
  },
];
