export const TOPICS = [
  { id: 51, name: 'Environment and Climate Change', category: 'TOPIC' },
  { id: 52, name: 'Politics and Government', category: 'TOPIC' },
  { id: 53, name: 'Education and Learning', category: 'TOPIC' },
  { id: 54, name: 'Health and Wellness', category: 'TOPIC' },
  { id: 55, name: 'Science and Technology', category: 'TOPIC' },
  { id: 56, name: 'Travel and Adventure', category: 'TOPIC' },
  { id: 57, name: 'Arts and Culture', category: 'TOPIC' },
  { id: 58, name: 'Business and Finance', category: 'TOPIC' },
  { id: 59, name: 'Sports and Fitness', category: 'TOPIC' },
  { id: 510, name: 'History and Heritage', category: 'TOPIC' },
  {
    id: 511,
    name: 'Relationships and Personal Development',
    category: 'TOPIC',
  },
  { id: 512, name: 'Food and Cooking', category: 'TOPIC' },
  { id: 513, name: 'Entertainment and Pop Culture', category: 'TOPIC' },
  { id: 514, name: 'Lifestyle and Fashion', category: 'TOPIC' },
  { id: 515, name: 'Spirituality and Philosophy', category: 'TOPIC' },
];
