export const TOPICS = [
  { id: 1, name: 'Environment and Climate Change' },
  { id: 2, name: 'Politics and Government' },
  { id: 3, name: 'Education and Learning' },
  { id: 4, name: 'Health and Wellness' },
  { id: 5, name: 'Science and Technology' },
  { id: 6, name: 'Travel and Adventure' },
  { id: 7, name: 'Arts and Culture' },
  { id: 8, name: 'Business and Finance' },
  { id: 9, name: 'Sports and Fitness' },
  { id: 10, name: 'History and Heritage' },
  { id: 11, name: 'Relationships and Personal Development' },
  { id: 12, name: 'Food and Cooking' },
  { id: 13, name: 'Entertainment and Pop Culture' },
  { id: 14, name: 'Lifestyle and Fashion' },
  { id: 15, name: 'Spirituality and Philosophy' },
];
